### ISSUE TITLE
Using cya mydata <profilename> with EXCLUDE statements

### ISSUE THREAD

**Issue by JonTheNiceGuy** [cleverwise/cya#17]
It's not clear from the documentation, but I would like to be able to use `cya mydata jon` (with the following cya.conf file

```bash
MYDATA_jon="/home/jon/ /home/cya/jon"
EXCLUDE_/home/jon/="Dropbox/ Nextcloud/"
```

Is this currently possible?

**Comment by cleverwise** [comment]
At this time EXCLUDE does **not** work for mydata.  It is all or nothing for child directories.  I can add it to the list for future features but have no idea when I'll get to it.

**Comment by JonTheNiceGuy** [comment]
No worries, add it to the to-do list and if I get a chance, I'll see if I can write it :)

**Comment by cleverwise** [comment]
The mydata command doesn't use the same function calls as the system restore path, so it was never coded in due to time.  The mydata command was quickly added because I was tired of using other methods to backup user data.

So I quickly added it.  For the immediate needs I was interested in capturing all data and thus just skipped any EXCLUDE logic.  However I understand that can be useful in certain situations.  Plus if one has a mounted directory that would need to be skipped.  It is a very valid request.

So much to code on so many projects and so little time.  :-(
