### ISSUE TITLE
What if harddisk dies?

### ISSUE THREAD

**Issue by fethomm** [cleverwise/cya#23]
From what I understand, CYA needs to work in /home of the partition with the operating system you want to snapshot. So you are out of luck if your HDD/SDD dies? Is there no way to save the system on another HDD/SDD or an external drive?

**Comment by cleverwise** [comment]
If the data isn't backed up it will be lost (obviously).  However you are free to use standard backup methods for example mirroring hard drives or even backing up /home/cya/ to another hard drive.  You may mount /home/cya/ to another drive using fstab however that doesn't protect against that drive from failing either.  If you go this route you need to mount that drive during recovery.

Since one can always reinstall the OS in general few people bother with backing up the /home/cya/ directory.  CYA is developed more for accidental or malicious changes and not so much from hard drive failure.  However, as stated, you may backup /home/cya/ using your preferred tools and it would work.  If the hard drive fails and you have backed up /home/cya/ you can mount the new drive in another system, partition the drive, move the CYA data to the new drive, boot up off the rescue system and restore the OS as if nothing happened including all settings. It is technologically possible.

**Comment by fethomm** [comment]
Ok, thanks for that. I have quite a complex setup on my workstation and it would be a pain to have to set everything back up the way it is. And it would mean loosing income until it is resurrected. So I am happy to learn that there is ways to secure my setup with CYA. 

I actualy wroite an article on CYA for a German linux print magazine some months back and for that tested it on a seperate notebook, but never got around to using it productively for my own setup. Now I will. Thanks for your work!

**Comment by cleverwise** [comment]
Thanks for your support of the article.  That is very kind.

Your welcome.  I hope CYA helps.  I have several modifications I need to release when I get some time.

**Comment by fethomm** [comment]
To be honest, that is how I make my living. But I only write about Linux and related stuff, so that is more fun than  job. I will keep an eye out for your mods.
